architectury {
    common("fabric")
    common("neoforge")
}

loom {

}

dependencies {

    modImplementation("com.cobblemon:fabric:${property("cobblemon_version")}")
    // alL fabric dependencies:
    modImplementation("net.fabricmc:fabric-loader:${property("fabric_loader_version")}")
    modImplementation("net.fabricmc.fabric-api:fabric-api:${property("fabric_version")}")
    //modImplementation("net.neoforged:neoforge:${rootProject.neoforge_version}")

    modImplementation("dev.architectury:architectury:${property("architectury_version")}")

    // Lombok
    annotationProcessor("org.projectlombok:lombok:${property("lombok_version")}")
    implementation("org.projectlombok:lombok:${property("lombok_version")}")

    modImplementation(files("libs/CobbleUtils-common.jar"))
}


